### ISSUE TITLE
online converter adds a seemingly arbitrary start point representing the top of the artboard

### ISSUE THREAD

**Issue by heaversm** [camoconnell/lazy-line-painter#33]
Hi - I noticed that when you use the online converter to convert an svg file created in illustrator - it creates a start point at what I believe would be the top of the artboard in illustrator, at the X coordinate where the art would start (but not the Y coordinate). I've attached two images, one of which is drawn by the converter, and the other representing what is desired.

I was able to fix the code in all cases by removing the first set of coordinates in the move commandand moving the first set of coordinates in the line command to the move command. Thus instead of 

`M [X1],[Y1] L [X2],[Y2] [X3],[Y3] ...`

you would have

`M [X2],[Y2] L [X3],[Y3] ...`

I've also posted my SVG file here:

http://mikeheavers.com/transfers/test.svg

![screen shot 2015-01-12 at 9 53 10 am](https://cloud.githubusercontent.com/assets/520541/5704642/6ba3d81a-9a41-11e4-9cac-8f9bebb6b1d4.png)
![screen shot 2015-01-12 at 9 53 16 am](https://cloud.githubusercontent.com/assets/520541/5704643/6ba875fa-9a41-11e4-8b72-5a8d06cc2bef.png)

Across multiple paths, you get a sort of "etch-a-sketch" effect in which the path drawer doesn't pick up its pen.
![screen shot 2015-01-12 at 10 00 34 am](https://cloud.githubusercontent.com/assets/520541/5704721/eeeadf66-9a41-11e4-9732-86a12b795276.png)
![screen shot 2015-01-12 at 10 00 49 am](https://cloud.githubusercontent.com/assets/520541/5704722/eeeeb5dc-9a41-11e4-92b6-1663997424b6.png)

Regardless, thanks for a great library - will still save me lots of time with what I'm trying to build.

**Comment by drduan** [comment]
What you means ?



drduan@vip.qq.com
 
From: Mike Heavers
Date: 2015-01-12 22:58
To: camoconnell/lazy-line-painter
Subject: [lazy-line-painter] online converter adds a seemingly arbitrary start point representing the top of the artboard (#33)
Hi - I noticed that when you use the online converter to convert an svg file created in illustrator - it creates a start point at what I believe would be the top of the artboard in illustrator, at the X coordinate where the art would start (but not the Y coordinate). I've attached two images, one of which is drawn by the converter, and the other representing what is desired.
I was able to fix the code in all cases by removing the first set of coordinates in the move commandand moving the first set of coordinates in the line command to the move command. Thus instead of 
M [X1],[Y1] L [X2],[Y2] [X3],[Y3] ...
you would have
M [X2],[Y2] L [X3],[Y3] ...
I've also posted my SVG file here:
http://mikeheavers.com/transfers/test.svg

**Comment by inorganik** [comment]
That's odd, I've used Illustrator for all my svg exports and have never had that happen... you might try hitting cmd+Y and looking for stray points to delete. 

Ultimately, the svg conversion tool should be eliminated completely and all the processing done with JS. I've bugged Cam about this before... Cam are you ready to open-source the conversion tool?

**Comment by heaversm** [comment]
@inorganik  - agreed that the converter would be great as a standalone codebase. No stray points (my method is just doing select all) - though it may be something with how the lines were drawn - I was tracing a drawing, using the line tool sometimes and the pen tool others - when using the line tool I often joined multiple paths. Who knows - the svg file itself seems pretty clean at first glance, though @camoconnell it sounds like you'd be more familiar with the intricacies of the conversion. 

One last clarification that might be worth mentioning more explicitly on the site or in the readme is that the code looks for a div element with the same ID as the name of the file, so for example because my file was called test2, it created a path object called test2. By default, the jquery piece of the generated code references a DOM element called undefined:

```
 $(document).ready(function(){
 $('#undefined').lazylinepainter(
 {
    "svgData": pathObj,
    "strokeWidth": 2,
    "strokeColor": "#e09b99"
}).lazylinepainter('paint');
 });
```

But even when you change `#undefined` to the name of your actual DOM element, say `#test` - you will get an error around line 62 of the uncompressed library stating that your target is undefined. This is because it is looking for something in the object called "test2" since that was the name of the path object the online converter generated. 

There is a brief mention of the overrideKey option, which is where you would specify "test2", in the above scenario, but it is a bit unclear what value is needed there.

**Comment by camoconnell** [comment]
Closing old issues.
Composer has been rewritten from ground up
