### ISSUE TITLE
Animation on viewport and reset?

### ISSUE THREAD

**Issue by karoomii** [camoconnell/lazy-line-painter#71]
Is there a way I can have the animation start only when it enters the viewport? And could I have it reset so that every time someone scrolls back to it, it runs the animation again?

Thank you!

**Comment by camoconnell** [comment]
For future reference;
_"Is there a way I can have the animation start only when it enters the viewport?"_ - this would be managed by the developer integrating this lib.

"And could I have it reset so that every time someone scrolls back to it, it runs the animation again?" - Calling paint() on your lazyline instance will replay the animtion. 

Check the example folder for a comprehensive demo of functionality supported by lazylinepainter
